# Generated by Django 3.2.16 on 2024-05-11 15:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deflator',
            fields=[
                ('year_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(2024)], verbose_name='Год')),
                ('deflator', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Коэффициент')),
            ],
        ),
        migrations.CreateModel(
            name='RateType',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(verbose_name='Ставка')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INN', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='ИНН')),
                ('inc_per_quartal', models.PositiveIntegerField(default=0, verbose_name='Доход за квартал')),
                ('ins_prem', models.PositiveIntegerField(default=0, verbose_name='Страховые взносы')),
                ('tax_rate', models.ForeignKey(db_column='rate_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.ratetype', verbose_name='Ставка по налогу')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.deflator', verbose_name='Год')),
            ],
        ),
    ]
