# Generated by Django 3.2.16 on 2024-05-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='trade_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма уплаченного торгового сбора'),
        ),
    ]
