# Generated by Django 3.2.16 on 2024-05-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_proposal_trade_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='trade_fee',
            new_name='trade_fee_paid',
        ),
    ]
